# -*- mode: ruby -*-
# vi: set ft=ruby :

def get_bridge_adapter()
  return %x{ip route | grep default | head -n 1 | awk '{ print $5 }'}.chomp
end

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.define "ub1404" do |ub1404|
    ub1404.vm.box = "rapid7/metasploitable3-ub1404"
    ub1404.vm.hostname = "metasploitable3-ub1404"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    config.vm.network :public_network, bridge: get_bridge_adapter(), ip: ENV['METASPLOITABLE3_IP']

    ub1404.vm.provider "virtualbox" do |v|
      v.name = "Metasploitable3-ub1404"
      v.memory = 2048
    end
  end
end
