apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: default
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31547
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nextcloud
