apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: default
  labels:
    app.kubernetes.io/name: nextcloud
type: Opaque
data:
  nextcloud-password: Y2hhbmdlbWU=
  nextcloud-username: YWRtaW4=
